BOT_TOKEN = "توکن رباتت اینجا بذار"
WC_URL = "https://www.jamakshop.ir/wp-json/wc/v3"
WC_KEY = "کلید مصرف‌کننده"
WC_SECRET = "رمز مصرف‌کننده"
SUPPORT_USERNAME = "sif39"
NEWSLETTER_EMAIL = "sif3940@gmail.com"
SITE_URL = "https://www.jamakshop.ir"
INSTAGRAM_URL = "https://instagram.com/jamakshop1"